### ISSUE TITLE
Error while creating hive transactional  tables

### ISSUE THREAD

**Issue by UdayChokkam** [HiveRunner/HiveRunner#158]
**Describe the bug**
I am trying to create a hive  transactional table (TBLPROPERTIES('COLUMN_STATS_ACCURATE' = 'true', 'orc.compress' = 'ZLIB', 'transactional' = 'true') to insert  test data which needs to be available to test my hive queries with hive runner

**To Reproduce**
1. Brought up a docker container from image https://github.com/dwp/docker-hiverunner which has hive runner in it 
2. It was working fine as expected until I tried creating a hive  transactional table (TBLPROPERTIES('COLUMN_STATS_ACCURATE' = 'true', 'orc.compress' = 'ZLIB', 'transactional' = 'true')
3. to reproduce create a table with the below 
CLUSTERED BY (any_column) INTO 1 BUCKETS
 ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.orc.OrcSerde'
 STORED AS ORC
 TBLPROPERTIES('COLUMN_STATS_ACCURATE' = 'true', 'orc.compress' = 'ZLIB', 'transactional' = 'true'); 

4. Add the below properties to hive configuration

 map.put("hive.txn.manager", "org.apache.hadoop.hive.ql.lockmgr.DbTxnManager");
        map.put("hive.support.concurrency", "true");
        map.put("hive.enforce.bucketing", "true");
        map.put("hive.exec.dynamic.partition.mode", "nostrict");
        map.put("hive.compactor.initiator.on", "true");
        map.put("hive.compactor.worker.threads", "1");

**Expected behavior**
Hive transactional table should be created without issues 

**Logs**
Unable to select from transaction database java.sql.SQLSyntaxErrorException: Table/View 'NEXT_TXN_ID' does not exist. 
 at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source) 
 at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source) 
 at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source) 
 at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source) 
 at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source) 
 at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source) 
 at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source) 
 at org.apache.derby.impl.jdbc.EmbedStatement.executeQuery(Unknown Source) 
 at org.apache.hadoop.hive.metastore.txn.TxnHandler.openTxns(TxnHandler.java:594) 
 at org.apache.hadoop.hive.metastore.txn.TxnHandler.openTxns(TxnHandler.java:551) 
 at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.open_txns(HiveMetaStore.java:7155) 
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
 at java.lang.reflect.Method.invoke(Method.java:498) 
 at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invokeInternal(RetryingHMSHandler.java:147) 
 at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invoke(RetryingHMSHandler.java:108) 
 at com.sun.proxy.$Proxy27.open_txns(Unknown Source) 
 at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.openTxnsIntr(HiveMetaStoreClient.java:2473) 
 at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.openTxn(HiveMetaStoreClient.java:2437) 
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
 at java.lang.reflect.Method.invoke(Method.java:498) 
 at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:212) 
 at com.sun.proxy.$Proxy28.openTxn(Unknown Source) 
 at org.apache.hadoop.hive.ql.lockmgr.DbTxnManager.openTxn(DbTxnManager.java:246) 
 at org.apache.hadoop.hive.ql.lockmgr.DbTxnManager.openTxn(DbTxnManager.java:230) 
 at org.apache.hadoop.hive.ql.Driver.openTransaction(Driver.java:903) 
 at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:655) 
 at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1826) 
 at org.apache.hadoop.hive.ql.Driver.compileAndRespond(Driver.java:1773) 
 at org.apache.hadoop.hive.ql.Driver.compileAndRespond(Driver.java:1768) 
 at org.apache.hadoop.hive.ql.reexec.ReExecDriver.compileAndRespond(ReExecDriver.java:126) 
 at org.apache.hive.service.cli.operation.SQLOperation.prepare(SQLOperation.java:197) 
 at org.apache.hive.service.cli.operation.SQLOperation.runInternal(SQLOperation.java:260) 
 at org.apache.hive.service.cli.operation.Operation.run(Operation.java:247) 
 at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementInternal(HiveSessionImpl.java:541) 
 at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatement(HiveSessionImpl.java:510) 
 at org.apache.hive.service.cli.CLIService.executeStatement(CLIService.java:267) 
 at com.klarna.hiverunner.HiveServerContainer.executeStatement(HiveServerContainer.java:120) 
 at com.klarna.hiverunner.builder.HiveShellBase.executeStatementsWithCommandShellEmulation(HiveShellBase.java:115) 
 at com.klarna.hiverunner.builder.HiveShellBase.executeScriptWithCommandShellEmulation(HiveShellBase.java:104) 
 at com.klarna.hiverunner.builder.HiveShellBase.executeScriptsUnderTest(HiveShellBase.java:324) 
 at com.klarna.hiverunner.builder.HiveShellBase.start(HiveShellBase.java:165) 

**Versions (please complete the following information):**
 - HiveRunner Version: 6.0.1
 - Hive Versions: 3.1.2

**Additional context**
I see table 'NEXT_TXN_ID' part of the metastore tables 
https://github.com/apache/hive/blob/7b3ecf617a6d46f48a3b6f77e0339fd4ad95a420/metastore/scripts/upgrade/derby/hive-txn-schema-0.14.0.derby.sql#L42
However not sure why that table is not available in the derby  metastore

**Comment by massdosage** [comment]
I'm trying to reproduce this issue via a unit test. I've created a *very* simple one that attempts to do what you describe above, take a look at https://github.com/HiveRunner/HiveRunner/blob/issue-158/src/test/java/com/klarna/hiverunner/TransactionalTablesTest.java. This is currently succeeding - I don't see the issue you report above. Is there something I'm missing in the test?

**Comment by massdosage** [comment]
Closing due to inactivity and inability to reproduce. If this is still an issue and a unit test can be written to reproduce it please re-open. One of the Hive developers suggested we could call the Hive `TxnDbUtil.prepDb` method to set up the database.
